# Generated by Django 5.1.7 on 2025-03-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=25, null=True)),
                ('foto_user', models.ImageField(upload_to='fotos')),
                ('pagamentp', models.BooleanField(default=True)),
                ('sintomas', models.CharField(choices=[('TDAH', 'TRANSTORNO DE DEFICIT DE ANTEÇÃO E HIPERATIVIDADE'), ('D', 'DEPRESSAO'), ('A', 'ANSIEDADE'), ('TAG', 'TRANSTORNO DE ANSIEDADE GENERALIZADA')], max_length=4)),
            ],
        ),
    ]
