# Generated by Django 5.1.7 on 2025-03-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='foto_user',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='pagamentp',
            new_name='pagamento',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='sintomas',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='queixa',
            field=models.CharField(choices=[('TDAH', 'TRANSTORNO DE DEFICIT DE ATENÇÃO E HIPERATIVIDADE'), ('DEP', 'DEPRESSÃO'), ('ANS', 'ANSIEDADE'), ('TAG', 'TRANSTORNO DE ANSIEDADE GENERALIZADA')], default='sem', max_length=6),
            preserve_default=False,
        ),
    ]
